######################## default configuration ####################
baseURL = "/"
languageCode = "en-us"
title = "@sagrudd"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "sagrudd"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = "available on request"
email = "stephen@mnemosyne.co.uk"
location = "Dingelstedt, Germany"
# copyright
copyright = "| copyright &copy; 2021 @sagrudd |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = false



# cookies
[params.cookies]
enable = false
expire_days = 10


############################# social site ########################
[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/sagrudd"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/sagrudd/"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/sagrudd/"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/stephen-rudd-27650a1/"
